# backend/config.py
DB_CONFIG = {
    "host": "127.0.0.1",
    "user": "root",          # change if you use a different user
    "password": "Prabhu12#*",  # dev MySQL password (docker)
    "database": "apas"
}

EMAIL_CONFIG = {
    "SMTP_SERVER": "smtp.gmail.com",
    "SMTP_PORT": 587,
    "EMAIL": "your_gmail_here@gmail.com",
    "PASSWORD": "your_app_password_here"
}

# Encryption / TLS settings
# For production: set `APAS_FERNET_KEY` env var to a 32-byte urlsafe base64 key (Fernet key)
# or place the key file at the path below. Keep this secret out of source control.
ENCRYPTION = {
    "FERNET_KEY_PATH": "./secrets/fernet.key",  # generated by helper script for dev
    # HMAC secret for deterministic lookup (use env var APAS_HMAC_KEY in production)
    "HMAC_KEY_PATH": "./secrets/hmac.key"
}

# TLS / HTTPS configuration
# Provide file paths to your certificate and private key. For development you can
# generate a self-signed cert (see `scripts/generate_dev_cert.sh`).
TLS = {
    "CERT_PATH": "./secrets/server.crt",
    "KEY_PATH": "./secrets/server.key",
    # enforce secure minimum TLS version in the app
}